### ISSUE TITLE
Add notUsed helper function

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#124]
We need a helper function to assign error codes to specific values.
e.g. notUsed('0'|-8886) would return error value for any 0's in source table.

**Comment by pedrogit** [comment]
How is this different from GreaterThan(val, 0, TRUE|-8886)?

**Comment by prvernier** [comment]
This case applies to one set of attributes so far: DIST_EXT_UPPER_1 - DIST_EXT_UPPER_3 and DIST_EXT_LOWER_1 - DIST_EXT_LOWER_3 for the AB06 and AB16 inventories. The issue is that the FRI includes 0 values whereas the CASFRI species 1-100. The 0 values are not wrong but they should really be integer versions of empty strings (not null values).

A slight modification: notUsed(dist_ext_upper_1, 0, -8889)

**Comment by prvernier** [comment]
The reason the CASFRI doesn't specify 0, I assume, is that if there has been a disturbance then the value of this attribute cannot be 0. So, the 0 must be an indicator that not measurement was taken or something like that.

**Comment by pedrogit** [comment]
For other inventories, what is the source value (NULL?) when there is no disturbance and how does it translate into CAS?

**Comment by prvernier** [comment]
The BC and NB inventories don't appear to have these attributes.

**Comment by prvernier** [comment]
I need to take another look at the disturbance attributes in Alberta, because I now see that values can exceed 5.

**Comment by pedrogit** [comment]
The main question is actually "What does the CASFRI state for these attributes when there is no disturbance?" It probably doesn't state anything and that's a problem. We were probably leaving the field empty or with some error code. Seems to me that if there is no disturbance then the error should be NOT_APPLICABLE (-8887).

I see that the short definition for NOT_APPLICABLE is merely "Target attribute not in source table" but it could be more flexible: "Target attribute not in source table or no value in this context" and you explain in the CAS spec what this context is.

Another way would be to split this in two different codes: 

- NO_SOURCE_EQUIVALENT for when there is no source attribute equivalent to this target attribute

and 

- NOT_APPLICABLE when no value is applicable in the context of the actual row.

**Comment by prvernier** [comment]
There are 3 attributes relevant to disturbances in AB16:
  1. disturbance type - which is an empty string ("") when no disturbance code is assigned.
  2. disturbance year - which has a value of zero (0) or the year of disturbance.
  3. disturbance extent - which is coded as an integer (0,1,2,3,4,5,6); null values exist.

AB16 Notes:
  * there are rare cases where a polygon has a disturbance year but no disturbance type (""); is this an error or omission for type or and error of commission for year? We don't know and probably shouldn't worry about it.
  * conversely there are many polygons with a disturbance type and no disturbance year (0); this makes sense this year of disturbance is not always known.
  * there is only one polygon with a disturbance extent of 6 (this is an error).
  * when there is no disturbance type (""), disturbance extent can null or 0 (mostly 0);  the AVI manual specifies that domain values should be 1-5. So, null values and zeros seem to indicate that extent was not known (or measured).

The simplest would be to treat each attribute independently rather than assume that there has to be a type for there to be a year and extent (even if it makes intuitive sense) etc.

**Comment by pedrogit** [comment]
Maybe we need to add UNKNOW_VALUE in the missing values part of the error code sheet? Or is NULL_VALUE sufficient?

**Comment by prvernier** [comment]
Yes, I would almost be tempted to treat both 0 and null as a null value for this attribute since both AVI and CAS only seem to care about non zero values. But how do we do that with our helper functions?

**Comment by prvernier** [comment]
We also need to decide on what code to assign disturbance year when it is 0. Probably null value as well?

**Comment by edwardsmarc** [comment]
I'd agree zero should be set to null in this case. Or just NOT_IN_SET using matchList(). If we want to set it to null we can use greaterThan(dist, '0', FALSE|NULL_VALUE); matchList(dist, {'1', '2', '3', '4', '5'}|NOT_IN_SET).

The first test would catch the zero's, then any non-zero values would be validated for NOT_IN_SET. Remember the validation rules get processed left to right so in the above example any zero's would be set to NULL_VALUE, then any 6's would be set to NOT_IN_SET, then any 1-5's would get translated.

As for the year, I'd argue it should be translated independently so we preserve as much of the original data as possible. A modeler might want the year even if there's no disturbance type, they might assume the disturbance to be fire for example for modelling purposes.

**Comment by prvernier** [comment]
Makes sense, and I agree we should treat the disturbance attributes independently.

**Comment by pedrogit** [comment]
Another possibility, since NULL_VALUE is reserved for true NULLs, it's not really an UNKNOW_VALUE and that it not not part of a set, would be to have a NULL_EQUIV for values equivalent to NULL but not true NULL. Remember that we must avoid to interpret the data. Translating 0 to something that means true NULL is maybe too much of an interpretation. Hence the NULL_EQUIV.

On how to do that with the existing helper function: depends on the type. Using a mixture of IsInt(), MatchList() and GreaterThan() as Marc and I showed above.

I guess we don't need notUsed() anymore?

**Comment by edwardsmarc** [comment]
Sounds reasonable.

I don't think we need notUsed() for now. We might need it in the future if this situation comes up again with text strings for example but for this case we can deal with it using the numeric functions.

**Comment by prvernier** [comment]
Sounds good, I will update the AB06 and AB16 DST tables later today.

**Comment by edwardsmarc** [comment]
Closing as we no longer need this function
