### ISSUE TITLE
TT_RepackStringList() and TT_Parsestringlist() do not work together properly

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/PostgreSQL-Table-Translation-Framework#144]
Here we have a text array:

SELECT unnest('{''a'',''b''}'::text[])

We can pack it:

SELECT tt_repackstringlist('{''aa'', ''b''}'::text[])

But when we parse the packed string:

SELECT unnest(tt_parsestringlist(tt_repackstringlist('{''aa'', ''b''}'::text[])))

We get 5 rows. We should get only 2 rows.

**Comment by pedrogit** [comment]
Another problem is that NULL does not get repacked properly, nor parsed properly:

SELECT tt_repackstringlist('{''aa'', NULL}'::text[])

gives:

"'{''aa'','NULL'}'"

so that:

SELECT CASE WHEN a IS NULL THEN 'isnull' ELSE 'isnotnull' END
FROM (SELECT unnest(tt_parsestringlist(tt_repackstringlist('{''aa'', NULL}'::text[]))) a) foo

does not work properly and 

SELECT tt_notNullEmptyOr(tt_repackstringlist('{''aa'', NULL}'::text[]))

fails...

**Comment by edwardsmarc** [comment]
*Problem 1*
- The issue here is that TT_RepackStringList() wraps all values in two sets of single quotes, and the whole text string in single quotes. e.g. '{''aa'',''b''}'
- This is because it is only used in the TT_TextFctEVal() where the query calling the helper function is built. The duplicate quotes are needed in the context of executing the query.
  - For example, this has invalid syntax: SELECT tt_Concat({'a','b','c'}::text, '-'::text);
  - But this works: SELECT tt_Concat('{''a'',''b'',''c''}'::text, '-'::text);
- Switching TT_RepackStringList() to use single quotes fixes your example, but breaks TT_TextFctEval.
- We would have to add another function that double quotes everything for use in TT_TextFctEval
  - e.g. TT_DoubleQuote(TT_RepackStringList('{''aa'', ''b''}'::text[]))

*Problem 2*
- The question here is how to append a NULL into an array?
- i.e. why does this fail:
  - SELECT CASE WHEN a IS NULL THEN 'isnull' ELSE 'isnotnull' END
FROM (SELECT array_append('{}', NULL::text) a) foo

**Comment by edwardsmarc** [comment]
Another way of framing *Problem 1* is that TT_RepackStringList() was never intended to be called directly by TT_ParseStringList(). It was only meant to pass the values to the helper functions in a format required by the engine. Once in the helper function the string list is back in the correct format to be parsed by TT_ParseStringList().

It's name is therefore misleading. We could split it into two functions such as TT_RepackStringList() which could be called directly by TT_ParseStringList(), and TT_RepackStringListForEngine() which double quotes everything for passing to the helper functions.

**Comment by pedrogit** [comment]
I realised that the way we encode stringlist is actually very close to the way PostgreSQL does. So I'm working on a solution that would simply cast string list to a string array. This has the advantege of getting rid of most of te regular expressions, which are generally a source of many problems.

**Comment by pedrogit** [comment]
That works by the way:

SELECT CASE WHEN a IS NULL THEN 'isnull' ELSE 'isnotnull' END
FROM (SELECT array_append('{}', NULL::text) a) foo

**Comment by edwardsmarc** [comment]
Really? I get 'isnotnull'.

**Comment by pedrogit** [comment]
Sorry. This:

SELECT CASE WHEN a IS NULL THEN 'isnull' ELSE 'isnotnull' END
FROM (SELECT unnest(array_append('{}', NULL::text)) a) foo
