### ISSUE TITLE
Stop validation helper function existance after the first row of source data has been processed

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/PostgreSQL-Table-Translation-Framework#29]

**Comment by pedrogit** [comment]
With the simplification done to prevent TT_FctExist to work, the engine got much faster. We'll review that after the beta.

**Comment by edwardsmarc** [comment]
* This might not be needed anymore. #58 moved the existence check for helper functions from TT_Translate to TT_ValidateTTable.

* New checkExistence argument in TT_Translate is now set to FALSE. If this was set to TRUE we might still want to implement this issue but I can't see why this would happen since we will always be calling TT_ValidateTTable.

**Comment by pedrogit** [comment]
So fixed I guess?

**Comment by edwardsmarc** [comment]
Not fixed!
TT_ValidateTTable is still called for every source row.
Function is existence is still called everytime TT_ValidateTTable is run.
Fix is probably to add a checkExistence argument to TT_ValidateTTable and turn it to FALSE after the first row has been processed.

Can probably add a counter to change the arguments

**Comment by pedrogit** [comment]
No need for a counter. Just set it to TRUE before the first parent loop and then to FALSE at the end of the parent loop.
