### ISSUE TITLE
ifelse() helper function needed for translation rules

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/PostgreSQL-Table-Translation-Framework#51]
Some attributes are calculated using two or more existing or derived attributes. For example, productive_for for the ab06 inventory is calculated as:

if_else(mod1!="CC" & species_1=="EMPTY_STRING" & (crown_closure_upper!=-9998 | height_upper!=-9999), "PP", "PF"))

In this case, mod1 is an original attribute in the ab06 inventory while the 3 others are created by the translation engine.

**Comment by edwardsmarc** [comment]
* Engine doesn't support non-word strings so we can't write any helper functions containing logical statements in the translation table (e.g. if_else('col1 != CC', Y, N).
* For now I'll write some CASFRI specific functions with these if else statements hard coded into the function.
* I'll need to know the logical statement for each attribute, and whether the statement differs by row. i.e. for the above if_else example, is the logical equation you provide applied to every row? If so all parameters can be hard-coded and the translation table would just include e.g. TT_ab06_productive_for()

**Comment by edwardsmarc** [comment]
For many attributes we expect to need complex and nested ifelse statements. We do not expect these to be generic helper functions, and likely each attribute will need it's own specific translation function that will just be called from the translation table.

I'm labeling this as low priority because we can't write the functions until we have figured out the complex rules and checked them.

**Comment by edwardsmarc** [comment]
Closing. We have now started writing custom helper functions.
