### ISSUE TITLE
Add features to TT_ValidateTTable

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#55]
* Currently TT_ValidateTTable loop through the translation table and returns a table of values accessible to the engine
  * target attribute
  * attribute type
  * an array of validation rules in the TT_RulesDef class allowing function name and args to be accessed by the engine.
  * translation rule in the TT_RulesDef class

Additional features:
* Check there are no null or empty values in translation table and that the values are of the propre type
* Check helper functions exists using TT_FctExist (If we check function exists here, do we still need to check it exists in TT_FctEval?)

**Comment by pedrogit** [comment]
If we check function exists here, do we still need to check it exists in TT_FctEval?

Good question. The question is: Is TT_FctEval() used outside of the TT_ValidateTTable() context? If yes then TT_FctEval() has to check. If not it does not, then it does not need to. The answer to this is yes. But maybe we want this optional because we know an other of our process already checked. So I would add a "checkExistence" option and make it TRUE by default, and make TT_Translate to passed is FALSE.

**Comment by edwardsmarc** [comment]
Split into new issues #59, #58, #57, #56
