### ISSUE TITLE
Translation engine fails with bc08_vri01_lyr.csv (rule_id: 12, 14, 16)

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/PostgreSQL-Table-Translation-Framework#63]
ERROR:  invalid input syntax for integer: "30.1000003814697"
CONTEXT:  SQL statement "SELECT TT_copy('30.1000003814697'::text)::integer"
PL/pgSQL function tt_textfcteval(text,text[],jsonb,anyelement) line 39 at EXECUTE
SQL statement "SELECT TT_TextFctEval($1, $2, $3, NULL::integer);"
PL/pgSQL function _tt_translate(name,name,name,name,text[],boolean,integer,boolean,boolean) line 53 at EXECUTE
PL/pgSQL function tt_translate_bc08(name,name,name,name,text[],boolean,integer,boolean,boolean) line 3 at RETURN QUERY
********** Error **********

ERROR: invalid input syntax for integer: "30.1000003814697"
SQL state: 22P02
Context: SQL statement "SELECT TT_copy('30.1000003814697'::text)::integer"
PL/pgSQL function tt_textfcteval(text,text[],jsonb,anyelement) line 39 at EXECUTE
SQL statement "SELECT TT_TextFctEval($1, $2, $3, NULL::integer);"
PL/pgSQL function _tt_translate(name,name,name,name,text[],boolean,integer,boolean,boolean) line 53 at EXECUTE
PL/pgSQL function tt_translate_bc08(name,name,name,name,text[],boolean,integer,boolean,boolean) line 3 at RETURN QUERY

**Comment by edwardsmarc** [comment]
* This is happening because TT_Copy now only accepts and returns text values. The engine casts the output text value to the target type class, in this case integer.
* Since the translation is trying to copy a double value to an integer output, the engine is crashing.
* The old version of the engine would have cast to an integer internally, so input 30.1111 would have produced output 30.
* I could add a parameter to TT_Copy() called 'round' or 'isInt'. If TRUE the function would return the rounded version of any numeric values. This would be set to FALSE by default in which case the non-rounded numeric would be returned (current behavior).
* Alternatively we could add a new helper function called TT_Round(). I almost prefer this option as it explicitly indicates in the translation table that we are converting a double to an integer.

**Comment by edwardsmarc** [comment]
Note that the translation table validates for IsNumeric but not IsInt. Other tables appear to use IsInt which would catch this and return an error value.

**Comment by prvernier** [comment]
The majority of values are integers with a few numeric values that are causing the problems. Theoretically, I think they should all be integers so it might be related to the conversion from file GDB to Postgres. Whichever solution you think is best is good with me.
