### ISSUE TITLE
Make release with May 31st features

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#73]
* Based on our semantic versioning rules, this should be a change in major version number because the engine won't work with the old translation tables, because a number of helper function signatures have changed.

* Is it appropriate to have a major version number change every time a helper functions gets updated? This could happen quite regularly, at least during development.

**Comment by pedrogit** [comment]
No because we are in beta mode. We can change whatever we want, it is considered like a minor change. Once we have released the first version (1.0.0), then every change to the API needing a change in existing translation files will have to increase the major version number. Otherwise they will just increase the minor number.
