### ISSUE TITLE
How to pass geometries to helper functions

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#78]
* Option 1
  * Geometries are passed as text to the helper function to maintain our text-only rule for helper functions.
    * Option 1a - engine casts the geometry value to text using ::text, helper function then needs to convert it back using ::geometry (e.g. x::geometry (Polygon, SRID#)). Issue with this is that the geometry cast needs to assign the geometry type (e.g. Polygon, MultiPolygon etc.) and the SRID. Geometry type will not always be the same. There could be further complications as this doesn't appear to be the recommended method in the documentation.
    * Option 1b - engine converts geometry to text using ST_AsText(). This is preferred as it maintains the geometry type in the text string. Helper function converts it back to a geometry using ST_GeomFromText(). The engine would have to recognize geometry types and instead of casting them with ::text it would use ST_AsText().
    * Option 1b as described here uses the WKT format for the conversion. We could also do the same thing but using the WKB format.
* Option 2
  * We break the text only helper function rule and pass geometries straight to the helper functions. This option simplifies the helper functions as they don't need to convert from text to geometries. The engine would need to recognize geometry types and pass them as geometries. Validating helper functions would be more complex as we would no longer have just text signatures.

* I prefer Option 1b. I can't find any examples of option 1a online. Engine edits to support the proper conversion would be a 1-line addition to TT_TextFctEval().

**Comment by pedrogit** [comment]
From my experiment SRID and geometry type are conserved when casting to text and then back to geometry. There is no need to explicitly provide them when casting. Here are two queries demontrating this:

SELECT ST_AsEWKT(ST_SetSRID(ST_MakePoint(10, 10), 4268)::text::geometry)

The point is first cast to text then back to geometry and the SRID is conserved.

SELECT ST_GeometryType(ST_Multi(ST_MakePolygon(ST_SetSRID(ST_GeomFromText('LINESTRING(0 0, 0 10, 10 10, 0 0)'), 4268)))::text::geometry)

The polygon is converted to a multipolygon, cast to text and then back to geometry and the ending geometry is still a multipolygon.

So that means simply casting to text should not be a problem.
