### ISSUE TITLE
Implement TT_GeoIntersection()

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#80]
* Intersect function for assigning values from intersecting table to the target table.
* Does the intersect, calculates the number of intersecting polygons
  * If 1, returns value from requested column
  * If >1, either:
    * return from the polygon with the largest area, or
    * return the lowest value, or
    * return the highest value

**Comment by pedrogit** [comment]
Typo in higestVal.

Would it be possible to implement TT_GeoIntersectText (by supporting int methods as well) very generically so that TT_GeoIntersectInt could become a wrapper around TT_GeoIntersectText?

There should not be two queries, one for counting the number of row returned and the actual intersection. Those queries are very costly. The result of the intersection should be stored in a way that we can count the number of result and decide which result is best afterward.

**Comment by edwardsmarc** [comment]
* Yes the wrapper should work.
* I was trying to write it with one query where the function generates a table with one row for each intersecting polygon. Then we could count the rows and return the values from the same table.
* But a RECORD variable can only store one row.
* I'll see if I can find another option.

**Comment by edwardsmarc** [comment]
https://dba.stackexchange.com/questions/35721/declare-variable-of-table-type-in-pl-pgsql

**Comment by pedrogit** [comment]
Actually to reflect the fact that this is a geo function and to follow PostGIS conventions it should be named TT_GeoIntersectionText() and TT_GeoIntersectionInt() and the validation rule should be TT_GeoIntersects()

**Comment by edwardsmarc** [comment]
closed with commit faaf0b14b9cb9f77b7f7bca11f1bbd8baf70f7df

**Comment by edwardsmarc** [comment]
Note this currently only works if intersect table and source table have unique names for geometry columns. Related to #93
