### ISSUE TITLE
Optionally stop and resume on translation error

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#86]
Related to discussion in #82.

When engine encounters an error in translation, it should optionally be able to stop and resume translation from the row causing the error.

**Comment by pedrogit** [comment]
The engine will stop in two cases at translation step:

- When a translation helper function generate an error and the stopOnTranslationError is set to TRUE as a parameter to TT_Translate() (otherwise an error code is generated)

- When an invalid parameter is passed to a translation function (this normally happen at the very beginning while processing the first row of values).

This was implemented as part of #141

Resume will be implemented as part of a future issue.
